version: "3.7"

services:
  item-app:
    image: ghcr.io/dwi-adhi-soegiarto/item-app:v1
    command: sh -c "npm install --production --unsafe-perm && npm run build"
    ports:
      - 80:8080
    working_dir: /app
    volumes:
      - ./:/app
    depends_on: 
      - item-db
  item-db:
    image: mongo:3
    volumes:
      - app-db:/data/db

volumes:
  app-db: