version: "3.8"

services:
  item-app:
    image: ghcr.io/dwi-adhi-soegiarto/item-app:v1    
    restart: always
	ports:
      - 80:8080    
    depends_on: 
      - item-db
  item-db:
    image: mongo:3
    volumes:
      - app-db:/data/db

volumes:
  app-db: